/*
 * UART_CONFG.h
 *
 *  Created on: Dec 8, 2019
 *      Author: shady
 */

#ifndef UART_CONFG_H_
#define UART_CONFG_H_
/*UART Initialization Settings*/
/*UART MODE --> ASYNCH_MODE			SYNCH_MODE*/
#define UART_MODE_SELECT				ASYNCH_MODE

/*PARTIY NUMBER --> DISABLED_PARITY		EVEN_PARITY		ODD_PARITY*/
#define	UART_PARITY_MODE				DISABLED_PARITY

/*STOP BITS --> ONE_STOP_BIT			TWO_STOP_BIT*/
#define UART_STOP_BIT_MODE				ONE_STOP_BIT

/*CHAR SIZE --> _5_BIT			_6_BIT		_7_BIT		_8_BIT		_9_BIT --> UCSZ2 has to be ONE*/
#define UART_CHAR_SIZE					_8_BIT

/*UART Receiver --> UART_RXEN		UART_RXDIS*/
#define UART_RX_STATE					UART_RXEN

/*UART Transmitter --> UART_TXEN		UART_TXDIS*/
#define UART_TX_STATE					UART_TXEN

/*UART Receiver INT--> UART_RX_COMPLETE_INT_EN		UART_RX_COMPLETE_INT_DIS*/
#define	UART_RX_COMPLETE_INT_STATE		UART_RX_COMPLETE_INT_DIS

/*UART Transmitter INT--> UART_TX_COMPLETE_INT_EN		UART_TX_COMPLETE_INT_DIS*/
#define	UART_TX_COMPLETE_INT_STATE		UART_TX_COMPLETE_INT_DIS

/*UDR empty INT -->UART_UDR_EMPTY_INT_EN		UART_UDR_EMPTY_INT_DIS*/
#define	UART_UDR_EMPTY_INT_STATE		UART_UDR_EMPTY_INT_DIS




#endif /* UART_CONFG_H_ */
